### ISSUE TITLE
Be specific about which keypair to use for launching an AMI.

### ISSUE THREAD

**Issue by b-long** [Bioconductor/coursehelper#1]
In [this section](https://github.com/Bioconductor/coursehelper/tree/1c3bbf0b5a7d18406a0b2927113a2fcc8e83b461#building-a-course-ami) of the (administrator) documentation, we say : 
> _Instantiate one of the standard Bioconductor AMIs._

However, we don't give guidance as to what AWS keypair should be used.  Obviously, the actual RSA key needs to be kept secure / privately, but the name _bioc-default_ (et. al) doesn't need to be a secret :smile: .  The important thing to keep secured is the `.pem` file.  In addition to naming the keypair, the location of the `.pem` file must be known.  It might be useful to devise a common workflow, in which each team member is assigned a keypair (with some naming convention), and each team member has a practice for managing their individual keypair.  Then, it might also be useful to describe granting ssh access for each team members public key (which we already keep in SCM) to the newly instantiated EC2 instance (e.g. adding to the `/home/ubuntu/.ssh/authorized_keys` file).

Also, since this topic would be applicable to multiple infrastructure projects.  We'd likely want to store the solution in a _meta_ repository like this one: https://github.com/Bioconductor/Bioconductor/wiki/Keypair-management .  That way, other infrastructure projects (the [prbot](https://github.com/Bioconductor/prbot), [SPB](https://github.com/Bioconductor/packagebuilder), [HubServer](https://github.com/Bioconductor/HubServer) ) can simply link to the common solution.

**Comment by b-long** [comment]
cc/ @vobencha @mtmorgan @dtenenba

**Comment by lshep** [comment]
This has been addressed in updated documentation
