### ISSUE TITLE
Outdated README.rdoc

### ISSUE THREAD

**Issue by b-long** [Bioconductor/coursehelper#3]
I don't think we want to necessarily maintain README.md and README.rdoc .  If that's the case, I think we should remove README.rdoc .

cc/ @vobencha @dtenenba

**Comment by vobencha** [comment]
I can transfer relevant info from the rdoc to md then remove rdoc.

**Comment by b-long** [comment]
Awesome, thanks @vobencha .  I'm not sure if there's much useful [info in the `.rdoc` at the moment](https://github.com/Bioconductor/coursehelper/blob/1c3bbf0b5a7d18406a0b2927113a2fcc8e83b461/README.rdoc).  It might be worth it for us to create a _"Bioconductor Common Ruby"_ document , (e.g. in the [meta repo](https://github.com/Bioconductor/Bioconductor/wiki)).  There we could describe some introductory items about our use of Ruby, `rbenv`, and Gemfile's .  Of course, that could be a long-running (evolving) task and there's no immediate need to create such a document.

**Comment by vobencha** [comment]
@dtenenba are you ok with removing README.rdoc? It looks like relevant info is captured in README.md. FYI, it looks like a section on adding the AMI to course materials (after a course) didn't get added.

**Comment by dtenenba** [comment]
Yes, you can remove it.
The documentation on adding stuff to course materials is at https://github.com/Bioconductor/bioconductor.org/blob/master/README.md#adding-course-material-to-the-spreadsheet .

**Comment by vobencha** [comment]
Thanks, forgot about that. I've added a link to the README.md and removed README.rdoc file from my branch. I think all changes to my branch are automatically included in the original pull request. If this isn't the case I can make another request.

**Comment by vobencha** [comment]
Done.
