### ISSUE TITLE
Describe some tests of Rstudio web interface

### ISSUE THREAD

**Issue by b-long** [Bioconductor/coursehelper#4]
Since the students in any course will rely on the Rstudio web interface, we should ensure that it works before forging an EC2 instance into an AMI.  

Following along with the steps that are described in the [coursehelper README](https://github.com/Bioconductor/coursehelper/tree/1c3bbf0b5a7d18406a0b2927113a2fcc8e83b461#building-a-course-ami), you'll launch an EC2 instance from a Bioconductor AMI.  Once you've launched the EC2 instance, you can view it's public IP of the instance by navigating to the [AWS console](https://console.aws.amazon.com/ec2/home?region=us-east-1#Instances:sort=desc:launchTime).  Next,  you'll be able to launch the Rstudio web interface by navigating to http://ec2-public-ip-address/ , since Rstudio is listening on port 80.  

One idea of a test scenario is the following : 
1. Login to Rstudio (using the credentials found [in the source code](https://github.com/Bioconductor/coursehelper/blob/1c3bbf0b5a7d18406a0b2927113a2fcc8e83b461/app/views/welcome/get_url_post.html.erb#L18-L21)).
2. At the R console, type `biocLite("hadley/devtools")`.  This will test installation of packages from GitHub.  If it succeeds, students should have no trouble working in the class.  

Also, as a reminder, since these AMIs may have application beyond Bioconductor courses.  It might be more appropriate to answer this issue using a meta repository as discussed in this issue: https://github.com/Bioconductor/coursehelper/issues/2

**Comment by lshep** [comment]
This has been addressed in updated documentation
